version: '3.2'

services:

  php-fpm:
    build: docker/php-fpm
    working_dir: /app
    volumes:
      - ./app:/app
      - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/8.2/fpm/conf.d/99-overrides.ini
      - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/8.2/cli/conf.d/99-overrides.ini

  web:
    image: nginx:alpine
    working_dir: /app
    volumes:
      - ./app:/app
      - ./docker/nginx/web.conf:/etc/nginx/conf.d/default.conf
      - ./app/runtime/nginx:/var/log/nginx
    ports:
      - 8081:80

#  frontend:
#    build: frontend
#    ports:
#      - 20080:80
#    volumes:
#      # Re-use local composer cache via host-volume
#      - ~/.composer-docker/cache:/root/.composer/cache:delegated
#      # Mount source-code for development
#      - ./:/app
#
#
#  backend:
#    build: backend
#    ports:
#      - 21080:80
#    volumes:
#      # Re-use local composer cache via host-volume
#      - ~/.composer-docker/cache:/root/.composer/cache:delegated
#      # Mount source-code for development
#      - ./:/app

  db:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=somepassword
      - MYSQL_DATABASE=url_monitor
      - MYSQL_USER=url_monitor
      - MYSQL_PASSWORD=testtest
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
        - 30006:3306

  #pgsql:
  #  image: postgres:9.5
  #  environment:
  #    - POSTGRES_DB=yii2advanced
  #    - POSTGRES_USER=yii2advanced
  #    - POSTGRES_PASSWORD=secret